version: '2'

services:

  jenkins:
    container_name: jenkins
    build:
        context: .
    ports:
      - '8080:8080'
#     - '8443:8443'
      - '50000:50000'
    environment:
      JENKINS_URL: http://localhost:8080/
      JENKINS_HOME: /var/lib/jenkins/
      DOCKER_HOST: tcp://proxy1:2375
    volumes:
      - jenkins_data:/var/lib/jenkins
    restart: unless-stopped
    networks:
      - jenkins-net
    depends_on:
      - docker_socket_proxy

  docker_socket_proxy:
    build:
      context: .
      dockerfile: docker-socket-proxy.Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      jenkins-net:
        aliases:
          - proxy1

volumes:
  jenkins_data:
    driver: local

networks:
  jenkins-net:
